apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xpu-device-plugin-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
        component: xpu-device-plugin
        app: xpu
        name: xpu-device-plugin-ds
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        component: xpu-device-plugin
        app: xpu
        name: xpu-device-plugin-ds
    spec:
      serviceAccount: xpu-device-plugin
      hostNetwork: true
      nodeSelector:
        xpu: "true"
      containers:
      - image: openxpu/xpu-device-plugin:v2.0.23
        name: xpu
        # Make this pod as Guaranteed pod which will never be evicted because of node's resource consumption.
        command:
          - xpu-device-plugin-v2
          - -logtostderr
          - --v=5
          - --memory-unit=GiB
        resources:
          limits:
            memory: "300Mi"
            cpu: "1"
          requests:
            memory: "300Mi"
            cpu: "1"
        env:
        - name: KUBECONFIG
          value: /etc/kubernetes/kubelet.conf
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
